### ISSUE TITLE
UART Reading bug

### ISSUE THREAD

**Issue by StormCh** [quentinmissler/pycom-firmwares#1]
Hey, there is a UART reading bug between Version 2.4 and 2.5. In Version 2.4 the serial data are correct. But in Version 2.5 there a corrupt.

The Following is an output of ATOM 1.60 with pymakr Plugin. Of course with the same device but different FWs.

read via 2.4 (Pycom MicroPython 1.20.2.r4 [v1.20.1.r2-363-ga37510c09-dirty] on 2021-10-28; GPy with ESP32)
`
ReadSerial, read 45 of 339 b'ZEBAX80;1008;015200f6;02;7c;1b;11;0;0;5;00;0\n' done -> ZEBAX80;1008;015200f6;02;7c;1b;11;0;0;5;00;0
OK

ReadSerial, read 45 of 534 b'ZEBAX79;09fd;01520117;0b;7f;1b;11;0;0;5;00;0\n' done -> ZEBAX79;09fd;01520117;0b;7f;1b;11;0;0;5;00;0
OK

ReadSerial, read 45 of 609 b'BCCBM68;05b4;0152011c;2f;7f;1a;15;0;0;5;00;0\n' done -> BCCBM68;05b4;0152011c;2f;7f;1a;15;0;0;5;00;0
OK

ReadSerial, read 45 of 900 b'ZEBAX80;1009;0153384b;2a;6f;1b;11;0;0;5;00;0\n' done -> ZEBAX80;1009;0153384b;2a;6f;1b;11;0;0;5;00;0
OK

ReadSerial, read 45 of 975 b'ZEBAX78;087f;015339d2;1c;7f;1b;11;0;0;5;00;0\n' done -> ZEBAX78;087f;015339d2;1c;7f;1b;11;0;0;5;00;0
OK

ReadSerial, read 45 of 1170 b'BCCBM68;05b5;01533c2e;22;7f;1a;15;0;0;5;00;0\n' done -> BCCBM68;05b5;01533c2e;22;7f;1a;15;0;0;5;00;0
OK

ReadSerial, read 45 of 1365 b'ZEBAX79;09fe;01533db0;27;7f;1b;11;0;0;5;00;0\n' done -> ZEBAX79;09fe;01533db0;27;7f;1b;11;0;0;5;00;0
OK

ReadSerial, read 45 of 1560 b'ZEBAX80;100a;0153429d;21;7f;1b;11;0;0;5;00;0\n' done -> ZEBAX80;100a;0153429d;21;7f;1b;11;0;0;5;00;0
OK
`

read via 2.5 (Pycom MicroPython 1.20.2.r5 [v1.20.1.r2-400-g1b1e869c5-dirty] on 2021-10-28; GPy with ESP32)
`
ReadSerial, read 45 of 342 b'ZEBAX80;1008;015200f6;02;7c;1b;11;0;0;5;00;0\n' done -> ZEBAX80;1008;015200f6;02;7c;1b;11;0;0;5;00;0
OK

ReadSerial, read 45 of 537 b'ZEBAX79;09fd;01520117;0b;7f;1b;11;0;0;5;00;0\n' done -> ZEBAX79;09fd;01520117;0b;7f;1b;11;0;0;5;00;0
OK

ReadSerial, read 45 of 612 b'BCCBM68;05b4;0152011c;2f;7f;1a;15;0;0;5;00;0\n' done -> BCCBM68;05b4;0152011c;2f;7f;1a;15;0;0;5;00;0
OK

ReadSerial, read 45 of 807 b'ZEBAX80;1009;0153384b;2a;6f;1b;11;0;0;5;00;0\n' done -> ZEBAX80;1009;0153384b;2a;6f;1b;11;0;0;5;00;0
OK

ReadSerial, read 45 of 1023 b'ZEBAX78;087f;015339d2;1c;7f;1b;11;;1b;11;0;0;' done -> ZEBAX78;087f;015339d2;1c;7f;1b;11;;1b;11;0;0;
ERROR

ReadSerial, read 45 of 1218 b'BCCBM68;05b5;01533c2e;22;7f;1a;15;0;0;5;00;0\n' done -> BCCBM68;05b5;01533c2e;22;7f;1a;15;0;0;5;00;0
OK

ReadSerial, read 45 of 1413 b'ZEBAX79;09fe;01533db0;27;7f;1b;11;0;0;5;00;0\n' done -> ZEBAX79;09fe;01533db0;27;7f;1b;11;0;0;5;00;0
OK

ReadSerial, read 45 of 1608 b'ZEBAX80;100a;0153429d;21;7f;00;0\nZEBAX79;09ff' done ->
ZEBAX80;100a;0153429d;21;7f;00;0
ZEBAX79;09ff
ERROR
`

**Comment by quentinmissler** [comment]
Hello, 

I don't really see what the error is.

 I reused the official pycom firmwares, I just modified the variable corresponding to the size of the floats.

Have you tried to reproduce your test on the official pycom versions?

**Comment by StormCh** [comment]
Hey, I can reproduce it also on official firmware, so I close this one.
